### ISSUE TITLE
[Bug]: ConcurrentModificationException

### ISSUE THREAD

**Issue by codetaylor** [Coders-After-Dark/Reskillable#46]
### Steps to Reproduce
Not entirely sure on this one...

I had two instances of MC open on the same box, connected via LAN. At the time this happened, I was just staring at the screen and thinking.

EDIT: The instance that was hosting the connection is the one that crashed and terminated.

### Crash Report

https://gist.github.com/codetaylor/19c09c12c0d4e1d14350c7f9f3d76e3b

```
...
[11:39:49] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@29358425:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_144]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_144]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_144]
	at codersafterdark.reskillable.api.data.PlayerDataHandler.cleanup(PlayerDataHandler.java:50) ~[PlayerDataHandler.class:?]
	at codersafterdark.reskillable.api.data.PlayerDataHandler$EventHandler.onServerTick(PlayerDataHandler.java:82) ~[PlayerDataHandler$EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_EventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
...
```

### Versions
```
| ID                | Version             | Source                                       |
|:----------------- |:------------------- |:-------------------------------------------- |
| minecraft         | 1.12.2              | minecraft.jar                                |
| mcp               | 9.42                | minecraft.jar                                |
| FML               | 8.0.99.99           | forgeSrc-1.12.2-14.23.2.2635.jar             |
| forge             | 14.23.2.2635        | forgeSrc-1.12.2-14.23.2.2635.jar             |
| artisanworktables | @@VERSION@@         | artisan-worktables_main                      |
| crafttweaker      | 4.1.6               | CraftTweaker2-MC1120-Main-1.12-4.1.6.457.jar |
| jei               | 4.8.5.159           | jei_1.12.2-4.8.5.159.jar                     |
| athenaeum         | @@VERSION@@         | athenaeum_main                               |
| reskillable       | 1.12.2-GRADLE:BUILD | Reskillable-1.12.2-1.0.0-SNAPSHOT.13.jar     |
| ctgui             | 1.0.0               | CraftTweaker2-MC1120-Main-1.12-4.1.6.457.jar |
| bookshelf         | 2.3.523             | Bookshelf-1.12.2-2.3.523.jar                 |
| gamestages        | 1.0.80              | GameStages-1.12.2-1.0.80.jar                 |
| blockrenderer     | 1.0.0               | BlockRenderer-1.0.0.jar                      |
```

**Comment by Lanse505** [comment]
This seems to have been a weird corner-case issue?
It's hopefully gonna get future-proofed with the switch to a player-capability instead of our current system.
However, that's still a bit in the future, for now, I'm gonna close this issue.
