### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by codetaylor** [Coders-After-Dark/Reskillable#60]
This occurs when hovering over a game stage unlockable that has a custom trait requirement and pressing shift.

```
...
java.lang.NullPointerException: Rendering screen
	at codersafterdark.reskillable.api.requirement.TraitRequirement.getToolTip(TraitRequirement.java:40)
	at codersafterdark.reskillable.api.data.RequirementHolder.addRequirementsToTooltip(RequirementHolder.java:92)
	at codersafterdark.reskillable.client.gui.GuiSkillInfo.makeUnlockableTooltip(GuiSkillInfo.java:177)
	at codersafterdark.reskillable.client.gui.GuiSkillInfo.func_73863_a(GuiSkillInfo.java:121)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
...
```

Full crash log: https://gist.github.com/codetaylor/58c09e010206f2719a77a7b700733808

Relevant script:

```js
mods.compatskills.GameStageUnlockable.addGameStageUnlockable(
  SKILL_STAGES.botany.novice, 
  "botany_novice", 
  0, 0, 
  "reskillable:gathering", 1, 
  "reskillable:gathering|4", "reskillable:farming|4", "stage|crafty"
);

// hovering over this one and pressing shift causes the error
mods.compatskills.GameStageUnlockable.addGameStageUnlockable(
  SKILL_STAGES.botany.adept, 
  "botany_adept", 
  0, 1, 
  "reskillable:gathering", 2, 
  "reskillable:gathering|16", "reskillable:farming|8", "reskillable:magic|4", "trait|compatskills:botany_novice"
);
```

Crafttweaker log:

```
[INITIALIZATION][CLIENT][INFO] Added Unlockable Trait: botany.novice With GameStage Link: botany_novice under Skill: reskillable:gathering
[INITIALIZATION][CLIENT][INFO] Unlockable Trait: botany_novice has requirements: [reskillable:gathering|4, reskillable:farming|4, stage|crafty]
[INITIALIZATION][CLIENT][INFO] Added Unlockable Trait: botany_adept With GameStage Link: botany_adept under Skill: reskillable:gathering
[INITIALIZATION][CLIENT][INFO] Unlockable Trait: botany.adept has requirements: [reskillable:gathering|16, reskillable:farming|8, reskillable:magic|4, trait|compatskills:botany_novice]
```

Please let me know if I've done something wrong or if I can provide any other information to help.

**Comment by Lanse505** [comment]
1) What does "SKILL_STAGES.botany.adept" point towards?
2) Are you using CompatSkills 1.1.0?

**Comment by codetaylor** [comment]
> What does "SKILL_STAGES.botany.adept" point towards?

`SKILL_STAGES.botany.adept` represents a gamestage string: `botany_adept`.

> Are you using CompatSkills 1.1.0?

Yes, according to the jar name anyway: 
```
| compatskills | 1.12.2-1.0.0 | CompatSkills-1.12.2-1.1.0.jar |
```

**Comment by Lanse505** [comment]
Hmm I'll have to dig into this.
The crash I've encountered before and it's caused by it trying to show a requirement for a trait that doesn't exist. Hence my confusion 🤔

**Comment by codetaylor** [comment]
So I just cloned and set up Reskillable in a dev env to set breakpoints and inspect stuff. Using the same versions of everything else and the same zs script I had no problems.

Next I'm going to test in an isolated instance using the publicly available jar files.

**Comment by codetaylor** [comment]
Eh... I'm gonna close this. I just tested again in my pack and *no problems*.

I must've derped somehow.
